display_name: MeRead
package_name: meread
maintainer:
  name: liuyuxin
  email: gvenusleo@gmail.com
priority: optional
section: x11
installed_size: 6604
essential: false
icon: assets/meread_round.png

postinstall_scripts:
  - echo "--------------- Welcom to MeRead ---------------\n  @author  liuyuxin\n  @email   gvenusleo@gmail.com\n  @website https://liuyu.xin\n  @github  https://github.com/gvenusleo/MeRead\n------------------------------------------------"
postuninstall_scripts:
  - echo "-------------------- MeRead --------------------\n  @author  liuyuxin\n  @email   gvenusleo@gmail.com\n  @website https://liuyu.xin\n  @github  https://github.com/gvenusleo/MeRead\n------------------------------------------------"

keywords:
  - RSS
  - Feed
  - Read

generic_name: A RSS reader built with flutter and designed with Material You.

categories:
  - Utility

startup_notify: true
